In [0]:
import numpy as np
import sklearn
import pandas as pd

In [0]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'
names = ['Class', 'id', 'Sequence']
data = pd.read_csv(url, names = names)

In [3]:
#Building our Dataset by creating a custom Pandas DataFrame
# Each column in a DataFrame is called a Series. Lets start by making a series for each column.

classes = data.loc[:, 'Class']
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object

In [4]:
# generate list of DNA sequences
sequences = list(data.loc[:, 'Sequence'])
dataset = {}

# loop through sequences and split into individual nucleotides
for i, seq in enumerate(sequences):
    
    # split into nucleotides, remove tab characters
    nucleotides = list(seq)
    nucleotides = [x for x in nucleotides if x != '\t']
    
    # append class assignment
    nucleotides.append(classes[i])
    
    # add to dataset
    dataset[i] = nucleotides
    
print(dataset[0])

['t', 'a', 'c', 't', 'a', 'g', 'c', 'a', 'a', 't', 'a', 'c', 'g', 'c', 't', 't', 'g', 'c', 'g', 't', 't', 'c', 'g', 'g', 't', 'g', 'g', 't', 't', 'a', 'a', 'g', 't', 'a', 't', 'g', 't', 'a', 't', 'a', 'a', 't', 'g', 'c', 'g', 'c', 'g', 'g', 'g', 'c', 't', 't', 'g', 't', 'c', 'g', 't', '+']

In [13]:
dframe = pd.DataFrame(dataset)
print(dframe)

   0   1   2   3   4   5   6   7   8    ... 97  98  99  100 101 102 103 104 105
0    t   t   g   a   t   a   c   t   c  ...   c   t   a   g   c   g   c   c   t
1    a   g   t   a   c   g   a   t   g  ...   g   a   g   a   c   t   g   t   a
2    c   c   a   t   g   g   g   t   a  ...   c   t   a   g   t   a   c   c   a
3    t   t   c   t   a   g   g   c   c  ...   t   g   g   a   c   t   g   g   c
4    a   a   t   g   t   g   g   t   t  ...   a   a   g   g   a   t   a   t   a
5    g   t   a   t   a   c   g   a   t  ...   g   c   g   c   a   c   c   c   t
6    c   c   g   g   a   a   g   c   a  ...   g   c   t   a   t   t   t   c   t
7    a   c   a   a   t   a   t   a   a  ...   a   g   g   t   g   c   a   t   a
8    a   t   g   t   t   g   g   a   t  ...   c   a   t   g   g   a   c   c   a
9    t   g   a   g   a   g   g   a   a  ...   t   a   a   t   c   a   g   a   t
10   a   a   a   t   a   a   a   a   t  ...   t   c   c   c   c   c   a   a   a
11   c   c   c   g   c   g   g   c   a  ...   t   g   t   a   t   a   t   t   a
12   g   a   t   t   t   g   g   a   c  ...   c   a   c   g   c   a   g   g   a
13   c   g   a   a   a   a   a   c   t  ...   t   g   c   c   t   g   a   g   t
14   t   t   g   t   t   t   t   t   g  ...   t   t   a   c   a   a   g   c   a
15   t   t   t   c   t   g   t   t   c  ...   g   c   a   t   a   t   a   c   a
16   g   g   g   g   g   g   t   g   g  ...   t   a   g   c   a   t   t   t   g
17   c   t   c   a   a   a   a   a   a  ...   t   a   a   g   c   a   g   c   g
18   g   c   a   a   c   a   a   t   c  ...   g   t   a   a   g   a   c   t   a
19   t   a   t   g   g   a   g   a   a  ...   a   c   g   c   g   c   c   a   g
20   t   c   t   t   a   g   c   c   g  ...   t   a   a   a   g   c   t   a   g
21   c   g   a   g   a   a   c   t   g  ...   t   g   g   a   t   g   g   a   c
22   g   c   g   t   a   g   a   g   a  ...   t   a   g   c   c   a   a   c   t
23   g   t   c   g   a   g   t   t   c  ...   t   c   a   t   t   c   g   g   c
24   t   g   t   t   g   t   c   a   g  ...   c   c   a   t   t   a   t   g   t
25   g   a   t   t   c   t   t   t   t  ...   c   g   g   g   g   g   g   g   a
26   g   t   a   g   t   g   c   g   c  ...   a   c   a   c   a   a   c   t   a
27   t   t   t   c   g   c   c   a   c  ...   t   t   t   a   g   t   t   c   t
28   t   g   t   g   a   c   t   g   g  ...   g   t   g   t   g   t   t   t   g
29   a   g   t   g   a   g   g   c   t  ...   c   t   a   a   g   c   c   t   g
30   a   t   t   a   a   t   a   a   t  ...   g   g   g   a   g   a   c   g   c
31   g   g   t   g   a   a   t   t   c  ...   g   a   g   a   t   a   g   a   a
32   t   t   t   t   c   t   g   a   t  ...   t   c   c   t   t   t   t   g   c
33   a   c   t   a   c   a   a   c   g  ...   g   t   t   g   t   c   t   g   t
34   t   g   g   g   a   a   c   a   t  ...   t   c   a   c   t   t   a   g   c
35   g   t   t   a   c   a   g   g   g  ...   t   t   g   t   t   c   c   g   a
36   t   t   t   t   t   g   c   t   t  ...   t   g   a   t   t   g   t   t   t
37   a   a   a   g   a   a   a   a   a  ...   t   g   c   t   g   t   g   t   t
38   t   c   t   t   g   a   t   t   a  ...   g   t   g   c   c   g   g   t   a
39   a   a   c   t   a   a   a   a   a  ...   c   a   t   t   t   g   a   t   g
40   a   a   a   a   a   c   g   a   t  ...   g   t   c   t   g   a   t   t   c
41   t   t   t   g   t   t   t   t   c  ...   c   t   t   g   a   t   t   t   c
42   g   c   g   a   g   a   c   t   g  ...   a   a   c   t   a   g   g   g   a
43   c   t   c   a   c   g   a   g   c  ...   a   c   t   a   a   g   t   c   a
44   g   a   t   t   g   a   g   c   a  ...   t   t   g   g   g   a   c   t   t
45   c   a   a   a   c   g   c   t   a  ...   g   g   c   a   g   c   a   g   c
46   g   c   a   c   c   t   c   t   t  ...   t   t   a   c   a   g   c   a   a
47   g   g   c   t   t   c   c   c   g  ...   t   g   t   g   g   t   c   a   a
48   g   c   c   a   c   c   a   a   a  ...   a   a   g   t   g   t   a   a   t
49   c   a   a   a   c   g   t   a   a  ...   a   a   g   g   a   c   a   g   c
50   t   t   c   c   g   t   c   c   a  ...   t   c   a   c   a   a   g   g   a
51   t   c   c   a   t   t   a   a   t  ...   c   a   g   c   c   a   g   a   a
52   g   g   c   a   g   t   t   g   g  ...   g   t   t   c   t   c   c   g   g
53   t   c   g   a   g   a   g   a   g  ...   c   t   a   t   a   a   t   g   a
54   c   c   g   c   t   g   a   a   t  ...   t   a   t   a   t   t   t   a   a
55   g   a   c   t   a   g   a   c   t  ...   t   t   g   c   a   t   c   a   c
56   t   a   g   c   g   t   t   a   t  ...   t   t   a   g   t   g   c   c   t
57   +   +   +   +   +   +   +   +   +  ...   -   -   -   -   -   -   -   -   -

[58 rows x 106 columns]

In [14]:
df = dframe.transpose()
print(df.iloc[:5])

  0  1  2  3  4  5  6  7  8  9  10 11 12  ... 45 46 47 48 49 50 51 52 53 54 55 56 57
0  t  a  c  t  a  g  c  a  a  t  a  c  g  ...  c  g  g  g  c  t  t  g  t  c  g  t  +
1  t  g  c  t  a  t  c  c  t  g  a  c  a  ...  a  c  g  c  a  t  c  g  c  c  a  a  +
2  g  t  a  c  t  a  g  a  g  a  a  c  t  ...  a  a  c  c  a  c  c  c  g  g  c  g  +
3  a  a  t  t  g  t  g  a  t  g  t  g  t  ...  a  c  t  a  a  c  a  a  a  c  t  c  +
4  t  c  g  a  t  a  a  t  t  a  a  c  t  ...  c  c  t  c  c  g  t  g  g  t  a  g  +

[5 rows x 58 columns]

In [18]:
# for clarity, lets rename the last dataframe column to class
df.rename(columns = {57: 'Class'}, inplace = True) 
print(df.iloc[:5])

   0  1  2  3  4  5  6  7  8  9 10 11  ... 46 47 48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  a  c  ...  g  g  g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  a  c  ...  c  g  c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  a  c  ...  a  c  c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  t  g  ...  c  t  a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  a  c  ...  c  t  c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]

In [19]:
df.describe()

          0    1    2    3    4    5    6  ...   51   52   53   54   55   56 Class
count   106  106  106  106  106  106  106  ...  106  106  106  106  106  106   106
unique    4    4    4    4    4    4    4  ...    4    4    4    4    4    4     2
top       t    a    a    c    a    a    a  ...    t    t    c    c    c    t     +
freq     38   34   30   30   36   42   38  ...   33   35   32   29   29   34    53

[4 rows x 58 columns]

In [20]:
#Recording value counts for each sequence

series = []
for name in df.columns:
    series.append(df[name].value_counts())
    
info = pd.DataFrame(series)
details = info.transpose()
print(details)

      0     1     2     3     4     5  ...    52    53    54    55    56  Class
t  38.0  26.0  27.0  26.0  22.0  24.0  ...  35.0  30.0  23.0  29.0  34.0    NaN
c  27.0  22.0  21.0  30.0  19.0  18.0  ...  21.0  32.0  29.0  29.0  17.0    NaN
a  26.0  34.0  30.0  22.0  36.0  42.0  ...  25.0  22.0  26.0  24.0  27.0    NaN
g  15.0  24.0  28.0  28.0  29.0  22.0  ...  25.0  22.0  28.0  24.0  28.0    NaN
+   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   53.0
-   NaN   NaN   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   53.0

[6 rows x 58 columns]

In [21]:
#The data is in string format, convert to numerical by using dummies
""
numerical_df = pd.get_dummies(df)
numerical_df.iloc[:5]

   0_a  0_c  0_g  0_t  1_a  1_c  ...  56_a  56_c  56_g  56_t  Class_+  Class_-
0    0    0    0    1    1    0  ...     0     0     0     1        1        0
1    0    0    0    1    0    0  ...     1     0     0     0        1        0
2    0    0    1    0    0    0  ...     0     0     1     0        1        0
3    1    0    0    0    1    0  ...     0     1     0     0        1        0
4    0    0    0    1    0    1  ...     0     0     1     0        1        0

[5 rows x 230 columns]

In [23]:
#Dropping class columns
df = numerical_df.drop(columns=['Class_-'])

df.rename(columns = {'Class_+': 'Class'}, inplace = True)
print(df.iloc[:5])

   0_a  0_c  0_g  0_t  1_a  1_c  1_g  ...  55_g  55_t  56_a  56_c  56_g  56_t  Class
0    0    0    0    1    1    0    0  ...     1     0     0     0     0     1      1
1    0    0    0    1    0    0    1  ...     0     0     1     0     0     0      1
2    0    0    1    0    0    0    0  ...     0     0     0     0     1     0      1
3    1    0    0    0    1    0    0  ...     0     1     0     1     0     0      1
4    0    0    0    1    0    1    0  ...     0     0     0     0     1     0      1

[5 rows x 229 columns]

In [0]:
from sklearn import model_selection

# Create X and Y datasets for training
X = np.array(df.drop(['Class'], 1))
y = np.array(df['Class'])

# define seed for reproducibility
seed = 1

# split data into training and testing datasets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=seed)

In [33]:
import warnings
warnings.filterwarnings("ignore")



from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# define scoring method
scoring = 'accuracy'

# Define models to train
names = ["Nearest Neighbors", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "SVM Linear", "SVM RBF", "SVM Sigmoid"]

classifiers = [
    KNeighborsClassifier(n_neighbors = 3),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    SVC(kernel = 'linear'), 
    SVC(kernel = 'rbf'),
    SVC(kernel = 'sigmoid')
]

models = zip(names, classifiers)

# evaluate each model in turn
results = []
names = []

for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state = seed)
    cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)
    print("Accuracy:", accuracy_score(y_test, predictions))
    print(classification_report(y_test, predictions))

Nearest Neighbors: 0.823214 (0.113908)
Accuracy: 0.7777777777777778
              precision    recall  f1-score   support

           0       1.00      0.65      0.79        17
           1       0.62      1.00      0.77        10

    accuracy                           0.78        27
   macro avg       0.81      0.82      0.78        27
weighted avg       0.86      0.78      0.78        27

Gaussian Process: 0.873214 (0.056158)
Accuracy: 0.8888888888888888
              precision    recall  f1-score   support

           0       1.00      0.82      0.90        17
           1       0.77      1.00      0.87        10

    accuracy                           0.89        27
   macro avg       0.88      0.91      0.89        27
weighted avg       0.91      0.89      0.89        27

Decision Tree: 0.733929 (0.205077)
Accuracy: 0.8148148148148148
              precision    recall  f1-score   support

           0       1.00      0.71      0.83        17
           1       0.67      1.00      0.80        10

    accuracy                           0.81        27
   macro avg       0.83      0.85      0.81        27
weighted avg       0.88      0.81      0.82        27

Random Forest: 0.671429 (0.244088)
Accuracy: 0.48148148148148145
              precision    recall  f1-score   support

           0       0.67      0.35      0.46        17
           1       0.39      0.70      0.50        10

    accuracy                           0.48        27
   macro avg       0.53      0.53      0.48        27
weighted avg       0.56      0.48      0.48        27

Neural Net: 0.875000 (0.096825)
Accuracy: 0.9259259259259259
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.83      1.00      0.91        10

    accuracy                           0.93        27
   macro avg       0.92      0.94      0.92        27
weighted avg       0.94      0.93      0.93        27

AdaBoost: 0.925000 (0.114564)
Accuracy: 0.8518518518518519
              precision    recall  f1-score   support

           0       1.00      0.76      0.87        17
           1       0.71      1.00      0.83        10

    accuracy                           0.85        27
   macro avg       0.86      0.88      0.85        27
weighted avg       0.89      0.85      0.85        27

Naive Bayes: 0.837500 (0.137500)
Accuracy: 0.9259259259259259
              precision    recall  f1-score   support

           0       1.00      0.88      0.94        17
           1       0.83      1.00      0.91        10

    accuracy                           0.93        27
   macro avg       0.92      0.94      0.92        27
weighted avg       0.94      0.93      0.93        27

SVM Linear: 0.850000 (0.108972)
Accuracy: 0.9629629629629629
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        17
           1       0.91      1.00      0.95        10

    accuracy                           0.96        27
   macro avg       0.95      0.97      0.96        27
weighted avg       0.97      0.96      0.96        27

SVM RBF: 0.737500 (0.117925)
Accuracy: 0.7777777777777778
              precision    recall  f1-score   support

           0       1.00      0.65      0.79        17
           1       0.62      1.00      0.77        10

    accuracy                           0.78        27
   macro avg       0.81      0.82      0.78        27
weighted avg       0.86      0.78      0.78        27

SVM Sigmoid: 0.569643 (0.159209)
Accuracy: 0.4444444444444444
              precision    recall  f1-score   support

           0       1.00      0.12      0.21        17
           1       0.40      1.00      0.57        10

    accuracy                           0.44        27
   macro avg       0.70      0.56      0.39        27
weighted avg       0.78      0.44      0.34        27

In [0]:
for name, model in models:
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(name)
    print(accuracy_score(y_test, predictions))
    print(classification_report(y_test, predictions))
    
# Accuracy - ratio of correctly predicted observation to the total observations. 
# Precision - (false positives) ratio of correctly predicted positive observations to the total predicted positive observations
# Recall (Sensitivity) - (false negatives) ratio of correctly predicted positive observations to the all observations in actual class - yes.
# F1 score - F1 Score is the weighted average of Precision and Recall. Therefore, this score takes both false positives and false